apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-mhf1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-mhf1
    app.kubernetes.io/part-of: ci10t-776-0004-app
  name: devfile-sample-mhf1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-mhf1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-mhf1
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0004-tenant/ci10t-776-0004-app/devfile-sample-mhf1@sha256:33422534b3332ab287f462fe02a090ca054f8a0fd01eb544a18617c968bcf70a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
